---
- name: "Fetch Kubectl latest version"
  ansible.builtin.uri:
    url: "https://dl.k8s.io/release/stable.txt"
    return_content: yes
  register: stable_kubectl_version

- name: "Debug kubectl version"
  ansible.builtin.debug:
    msg: "Detected stable kubectl version: {{ stable_kubectl_version.content }}"

- name: "Download Kubectl"
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ stable_kubectl_version.content }}/bin/linux/amd64/kubectl"
    dest: "{{ doe_main_directory }}/kubectl"

- name: "Set executable"
  ansible.builtin.file:
    path: "{{ doe_main_directory }}/kubectl"
    mode: "u+x"

- name: "Create Alias"
  ansible.builtin.import_tasks: ../internal/install_bashrc_line.yml
  vars:
    line_regexp: "^alias k="
    line_command: "alias k=kubectl"

- name: Fix bash completion for alias k in .bashrc
  ansible.builtin.include_tasks: ../internal/install_bashrc_line.yml
  vars:
    line_regexp: "^complete -F __start_kubectl k"
    line_command: "complete -F __start_kubectl k"

- name: Enable Bash Completion
  ansible.builtin.include_tasks: ../internal/install_bashrc_line.yml
  vars:
    line_regexp: "^source <(kubectl completion bash)"
    line_command: "source <(kubectl completion bash)"