---

- name: "Install kubectx"
  ansible.builtin.import_tasks: ../internal/github_release_download.yml
  vars:
    tool_friendly_name: kubectx
    tool_download_name: "kubectx_||version||_linux_x86_64.tar.gz"
    tool_repo_name: "ahmetb/kubectx"
    tool_is_archive: yes