---

- name: "Install kubens"
  ansible.builtin.import_tasks: ../internal/install_tool.yml
  vars:
    tool_friendly_name: kubens
    tool_download_name: "kubens_||version||_linux_x86_64.tar.gz"
    tool_repo_name: "ahmetb/kubectx"
    tool_is_archive: true
    line_regexp: "^alias kns="
    line_command: "alias kns=kubens"

