- name: Install Microsoft GPG Key for rpm
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: true
  become_user: root
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install Microsoft Repo from rpm package
  ansible.builtin.yum:
    name: https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm
    state: present
  become: true
  become_user: root
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install Microsoft GPG Key for apt
  ansible.builtin.apt_key:
    state: present
    url: https://packages.microsoft.com/keys/microsoft.asc
  become: true
  become_user: root
  when: ansible_distribution == "Ubuntu"

- name: Add Microsoft azure-cli repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
    state: present
  become: true
  become_user: root
  when: ansible_distribution == "Ubuntu"

- name: Install Azure CLI
  ansible.builtin.package:
    name: azure-cli
    state: present
  become: true
  become_user: root

- name: "Enable Azure subscription alias (azs)"
  ansible.builtin.include_tasks: ../internal/install_bashrc_line.yml
  vars:
    line_regexp: "^alias azs=\"az account set --subscription\""
    line_command: "alias azs=\"az account set --subscription\""
