---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Install test prerequisites
      ansible.builtin.package:
        state: installed
        name: sudo

    - name: "Include curioni.doe"
      ansible.builtin.include_role:
        name: "curioni.doe"
