- name: Install Vault
  ansible.builtin.package:
    name: vault
    state: present
  become: true
  become_user: root

- name: "Enable Vault bash completion"
  ansible.builtin.include_tasks: ../internal/install_bashrc_line.yml
  vars:
    line_regexp: "^complete -C /usr/bin/vault vault"
    line_command: "complete -C /usr/bin/vault vault"